export const userTypes = {
  SHOW_HIDE_MENU: "SHOW_HIDE_MENU",
  SHOW_SIGNIN_POPUP: "SHOW_SIGNIN_POPUP",
};
export const blogTypes = {
  FETCH_POSTS: "FETCH_POSTS",
  ALL_POSTS: "ALL_POSTS",
  GET_POST_BY_POST_ID:"GET_POST_BY_POST_ID",
  SAVE_POST_DETAILS:"SAVE_POST_DETAILS"
};


export const authTypes = {
    REGISTER_USER : "REGISTER_USER",
    SAVE_USER : "SAVE_USER"
}
