export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const GET_ALLBUMS_REQUESTED = 'GET_ALLBUMS_REQUESTED';
export const GET_ALLBUMS_SUCCESS = 'GET_ALLBUMS_SUCCESS';
export const GET_ALLBUMS_FAILED = 'GET_ALLBUMS_FAILED';